{
	"id": "SUSE-SU-2020:3563-1",
	"modified": "2020-11-30T15:53:59Z",
	"published": "2020-11-30T15:53:59Z",
	"related": [
		"CVE-2019-16056",
		"CVE-2019-20907",
		"CVE-2019-20916",
		"CVE-2019-5010",
		"CVE-2020-14422",
		"CVE-2020-26116",
		"CVE-2020-8492"
	],
	"summary": "Security update for python36",
	"details": "This update for python36 fixes the following issues:\n\nUpdate to 3.6.12, including the following fixes:\n\n- Fixed a directory traversal in _download_http_url() (bsc#1176262 CVE-2019-20916)\n- Fixed CRLF injection via HTTP request method in httplib/http.client (bsc#1177211 CVE-2020-26116)\n- Fixed possible infinite loop in specifically crafted tarball (bsc#1174091 CVE-2019-20907)\n- Fixed a CRLF injection via the host part of the url passed to urlopen() (bsc#1155094 CVE-2019-18348)\n- Reamed idle icons to idle3 in order to avoid conflicts with python2 (bsc#1165894)\n- Handful of compatibility changes between SLE15 and SLE12 (jsc#ECO-2799, jsc#SLE-13738, bsc#1179193)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server 12 SP5",
				"name": "python36",
				"purl": "pkg:rpm/suse/python36&distro=SUSE%20Linux%20Enterprise%20Server%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.12-4.22.2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.12-4.22.2",
						"python36": "3.6.12-4.22.2",
						"python36-base": "3.6.12-4.22.2"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server 12 SP5",
				"name": "python36-core",
				"purl": "pkg:rpm/suse/python36-core&distro=SUSE%20Linux%20Enterprise%20Server%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.12-4.22.2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.12-4.22.2",
						"python36": "3.6.12-4.22.2",
						"python36-base": "3.6.12-4.22.2"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server for SAP Applications 12 SP5",
				"name": "python36",
				"purl": "pkg:rpm/suse/python36&distro=SUSE%20Linux%20Enterprise%20Server%20for%20SAP%20Applications%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.12-4.22.2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.12-4.22.2",
						"python36": "3.6.12-4.22.2",
						"python36-base": "3.6.12-4.22.2"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Server for SAP Applications 12 SP5",
				"name": "python36-core",
				"purl": "pkg:rpm/suse/python36-core&distro=SUSE%20Linux%20Enterprise%20Server%20for%20SAP%20Applications%2012%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.12-4.22.2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.12-4.22.2",
						"python36": "3.6.12-4.22.2",
						"python36-base": "3.6.12-4.22.2"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2020/suse-su-20203563-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1149955"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1165894"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1174091"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1176262"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1177211"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-16056"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-20907"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-20916"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-5010"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-14422"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-26116"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-8492"
		}
	]
}
