{
	"id": "SUSE-SU-2020:1294-1",
	"modified": "2020-05-18T05:38:52Z",
	"published": "2020-05-18T05:38:52Z",
	"related": [
		"CVE-2019-18218"
	],
	"summary": "Security update for file",
	"details": "This update for file fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-18218: Fixed a heap-based buffer overflow in cdf_read_property_info() (bsc#1154661).\n\nNon-security issue fixed:\n\n- Fixed broken '--help' output (bsc#1169512).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Basesystem 15 SP1",
				"name": "file",
				"purl": "purl:rpm/suse/file&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Basesystem%2015%20SP1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.32-7.8.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"file": "5.32-7.8.1",
						"file-devel": "5.32-7.8.1",
						"file-magic": "5.32-7.8.1",
						"libmagic1": "5.32-7.8.1",
						"libmagic1-32bit": "5.32-7.8.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Development Tools 15 SP1",
				"name": "python-magic",
				"purl": "purl:rpm/suse/python-magic&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Development%20Tools%2015%20SP1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.32-7.8.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python3-magic": "5.32-7.8.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Python 2 15 SP1",
				"name": "python-magic",
				"purl": "purl:rpm/suse/python-magic&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Python%202%2015%20SP1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.32-7.8.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python2-magic": "5.32-7.8.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2020/suse-su-20201294-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1154661"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1169512"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-18218"
		}
	]
}
