{
	"id": "SUSE-SU-2024:2320-1",
	"modified": "2024-07-08T11:14:03Z",
	"published": "2024-07-08T11:14:03Z",
	"related": [
		"CVE-2024-37891"
	],
	"summary": "Security update for python-urllib3",
	"details": "This update for python-urllib3 fixes the following issues:\n\n- CVE-2024-37891: Fixed proxy-authorization request header not stripped during cross-origin redirects (bsc#1226469).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Public Cloud 15 SP4",
				"name": "python-urllib3",
				"purl": "pkg:rpm/suse/python-urllib3&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Public%20Cloud%2015%20SP4"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.0.7-150400.7.18.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-urllib3": "2.0.7-150400.7.18.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Python 3 15 SP5",
				"name": "python-urllib3",
				"purl": "pkg:rpm/suse/python-urllib3&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Python%203%2015%20SP5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.0.7-150400.7.18.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-urllib3": "2.0.7-150400.7.18.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Python 3 15 SP6",
				"name": "python-urllib3",
				"purl": "pkg:rpm/suse/python-urllib3&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Python%203%2015%20SP6"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.0.7-150400.7.18.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-urllib3": "2.0.7-150400.7.18.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.5",
				"name": "python-urllib3",
				"purl": "pkg:rpm/opensuse/python-urllib3&distro=openSUSE%20Leap%2015.5"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.0.7-150400.7.18.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-urllib3": "2.0.7-150400.7.18.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.6",
				"name": "python-urllib3",
				"purl": "pkg:rpm/opensuse/python-urllib3&distro=openSUSE%20Leap%2015.6"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.0.7-150400.7.18.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python311-urllib3": "2.0.7-150400.7.18.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242320-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1226469"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-37891"
		}
	]
}
