{
	"id": "SUSE-SU-2019:2370-1",
	"modified": "2019-09-12T11:30:43Z",
	"published": "2019-09-12T11:30:43Z",
	"related": [
		"CVE-2018-20060",
		"CVE-2019-11236",
		"CVE-2019-11324",
		"CVE-2019-9740"
	],
	"summary": "Security update for python-urllib3",
	"details": "This update for python-urllib3 fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-9740: Fixed CRLF injection issue (bsc#1129071).\n- CVE-2019-11324: Fixed invalid CA certificat verification (bsc#1132900).\n- CVE-2019-11236: Fixed CRLF injection via request parameter (bsc#1132663).\n- CVE-2018-20060: Remove Authorization header when redirecting cross-host (bsc#1119376).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Public Cloud 12",
				"name": "python-urllib3",
				"purl": "pkg:rpm/suse/python-urllib3&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Public%20Cloud%2012"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.22-3.14.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-urllib3": "1.22-3.14.1",
						"python3-urllib3": "1.22-3.14.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Manager Server 3.2",
				"name": "python-urllib3",
				"purl": "pkg:rpm/suse/python-urllib3&distro=SUSE%20Manager%20Server%203.2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.22-3.14.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-urllib3": "1.22-3.14.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Enterprise Storage 4",
				"name": "python-urllib3",
				"purl": "pkg:rpm/suse/python-urllib3&distro=SUSE%20Enterprise%20Storage%204"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.22-3.14.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-urllib3": "1.22-3.14.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Enterprise Storage 5",
				"name": "python-urllib3",
				"purl": "pkg:rpm/suse/python-urllib3&distro=SUSE%20Enterprise%20Storage%205"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.22-3.14.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-urllib3": "1.22-3.14.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2019/suse-su-20192370-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1119376"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1129071"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1132663"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1132900"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2018-20060"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-11236"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-11324"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2019-9740"
		}
	]
}
