{
	"id": "SUSE-SU-2022:0942-2",
	"modified": "2022-04-19T19:26:17Z",
	"published": "2022-04-19T19:26:17Z",
	"related": [
		"CVE-2021-3572"
	],
	"summary": "Security update for python3",
	"details": "This update for python3 fixes the following issues:\n\n- CVE-2021-3572: Fixed an improper handling of unicode characters in pip (bsc#1186819).\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Micro 5.2",
				"name": "python3",
				"purl": "purl:rpm/suse/python3&distro=SUSE%20Linux%20Enterprise%20Micro%205.2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.15-150300.10.21.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.15-150300.10.21.1",
						"python3": "3.6.15-150300.10.21.1",
						"python3-base": "3.6.15-150300.10.21.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Micro 5.2",
				"name": "python3-core",
				"purl": "purl:rpm/suse/python3-core&distro=SUSE%20Linux%20Enterprise%20Micro%205.2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.6.15-150300.10.21.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"libpython3_6m1_0": "3.6.15-150300.10.21.1",
						"python3": "3.6.15-150300.10.21.1",
						"python3-base": "3.6.15-150300.10.21.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20220942-2/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1186819"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2021-3572"
		}
	]
}
