{
	"id": "openSUSE-SU-2020:1014-1",
	"modified": "2020-07-19T18:25:49Z",
	"published": "2020-07-19T18:25:49Z",
	"related": [
		"CVE-2020-8903",
		"CVE-2020-8907",
		"CVE-2020-8933"
	],
	"summary": "Security update for google-compute-engine",
	"details": "This update for google-compute-engine fixes the following issues:\n\n- Don't enable and start google-network-daemon.service when it's\n  already installed (bsc#1169978)\n\n  + Do not add the created user to the adm (CVE-2020-8903),\n    docker (CVE-2020-8907), or lxd (CVE-2020-8933) groups\n    if they exist (bsc#1173258)",
	"affected": [
		{
			"package": {
				"ecosystem": "openSUSE:Leap 15.2",
				"name": "google-compute-engine",
				"purl": "pkg:rpm/opensuse/google-compute-engine&distro=openSUSE%20Leap%2015.2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "20190801-lp152.5.4.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"google-compute-engine-init": "20190801-lp152.5.4.1",
						"google-compute-engine-oslogin": "20190801-lp152.5.4.1",
						"google-compute-engine-oslogin-32bit": "20190801-lp152.5.4.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/QL6WIX4PNU5XVJCZJX66JTLS2DSJSYZC/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1169978"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1173258"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-8903"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-8907"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-8933"
		}
	]
}
