{
	"id": "SUSE-SU-2021:1313-1",
	"modified": "2021-04-26T07:12:15Z",
	"published": "2021-04-26T07:12:15Z",
	"related": [
		"CVE-2021-21330"
	],
	"summary": "Security update for python-aiohttp",
	"details": "This update for python-aiohttp fixes the following issues:\n\n- CVE-2021-21330: Fixed the way pure-Python HTTP parser interprets `//` (bsc#1184745)\n",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Public Cloud 15 SP1",
				"name": "python-aiohttp",
				"purl": "pkg:rpm/suse/python-aiohttp&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Public%20Cloud%2015%20SP1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.4.4-3.6.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-aiohttp-doc": "3.4.4-3.6.1",
						"python3-aiohttp": "3.4.4-3.6.1"
					}
				]
			}
		},
		{
			"package": {
				"ecosystem": "SUSE:Linux Enterprise Module for Public Cloud 15 SP2",
				"name": "python-aiohttp",
				"purl": "pkg:rpm/suse/python-aiohttp&distro=SUSE%20Linux%20Enterprise%20Module%20for%20Public%20Cloud%2015%20SP2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.4.4-3.6.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-aiohttp-doc": "3.4.4-3.6.1",
						"python3-aiohttp": "3.4.4-3.6.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.suse.com/support/update/announcement/2021/suse-su-20211313-1/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1184745"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2021-21330"
		}
	]
}
