{
	"id": "openSUSE-SU-2021:0117-1",
	"modified": "2021-01-19T15:26:14Z",
	"published": "2021-01-19T15:26:14Z",
	"related": [
		"CVE-2020-26215"
	],
	"summary": "Security update for python-jupyter_notebook",
	"details": "This update for python-jupyter_notebook fixes the following issue:\n\n- CVE-2020-26215: Fixed an open redirect vulnerability (boo#1180458).\n\nThis update was imported from the openSUSE:Leap:15.1:Update update project.",
	"affected": [
		{
			"package": {
				"ecosystem": "SUSE:Package Hub 15 SP1",
				"name": "python-jupyter_notebook",
				"purl": "purl:rpm/suse/python-jupyter_notebook&distro=SUSE%20Package%20Hub%2015%20SP1"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.7.7-bp151.3.3.1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"binaries": [
					{
						"python-jupyter_notebook-doc": "5.7.7-bp151.3.3.1",
						"python2-jupyter_notebook": "5.7.7-bp151.3.3.1",
						"python2-jupyter_notebook-lang": "5.7.7-bp151.3.3.1",
						"python2-jupyter_notebook-latex": "5.7.7-bp151.3.3.1",
						"python3-jupyter_notebook": "5.7.7-bp151.3.3.1",
						"python3-jupyter_notebook-lang": "5.7.7-bp151.3.3.1",
						"python3-jupyter_notebook-latex": "5.7.7-bp151.3.3.1"
					}
				]
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OH7ZP2LBWERB26YSK5VYEQ2JEDDJXUOG/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.suse.com/1180458"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2020-26215"
		}
	]
}
