{
	"id": "openSUSE-SU-2024:13749-1",
	"modified": "2024-08-15T21:44:15Z",
	"published": "2024-08-15T21:44:15Z",
	"related": [
		"CVE-2024-27351"
	],
	"summary": "python310-Django-4.2.11-1.1 on GA media",
	"details": "These are all security issues fixed in the python310-Django-4.2.11-1.1 package on the GA media of openSUSE Tumbleweed.",
	"references": [
		{
			"type": "ADVISORY"
		},
		{
			"type": "WEB",
			"url": "https://www.suse.com/security/cve/CVE-2024-27351"
		}
	]
}
